[env:m5stick-c]
platform = espressif32
board = m5stick-c
framework = arduino

; 1. Force the scanner to only compile what we explicitly #include
lib_ldf_mode = deep

; 2. Nuke the specific sensor library causing the crash
lib_ignore = DFRobot_GP8XXX

lib_deps = 
    m5stack/M5StickCPlus2
    tzapu/WiFiManager